### Prototyping dash app

In [1]:
import pandas as pd
import os
from utils import constants

In [2]:
import datetime

In [3]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [4]:
import dash

In [5]:
from dash.dependencies import Input, Output

In [6]:
import create_dash

In [7]:
df = create_dash.read_data()[0]

In [8]:
df.head()

,tvjid,fntid,rtaid,tvjtiempo,tvjfechaextraccion,fecha_extraccion,tiempo_extraccion,length,tvjtiempo/length
0,963044,1,70,41,2018-09-28 12:53:56.257808,2018-09-28,12:53:56.257808,7.3,5.616438
1,963045,1,70,41,2018-09-28 12:53:58.837850,2018-09-28,12:53:58.837850,7.3,5.616438
2,963046,1,70,43,2018-09-28 12:55:02.271486,2018-09-28,12:55:02.271486,7.3,5.890411
3,963047,1,70,40,2018-09-28 13:00:02.392514,2018-09-28,13:00:02.392514,7.3,5.479452
4,963048,1,70,37,2018-09-28 13:05:02.337994,2018-09-28,13:05:02.337994,7.3,5.068493

In [23]:
routes = create_dash.read_data()[1]

In [24]:
routes

,rtaid,rtanombre,rtatviajemax,rtatviajemin,rtahorariocomienzo,rtahorariofinal,rtaactivaferiados,rtafechacreacion,rtaactiva,rtaorigen,rtadestino,rtaletrero,length
0,70,Sectra_Casa,50,25,00:00:00,23:59:00,t,2018-09-28 12:53:26.055105,t,General Mackenna,Exequiel FernÃ¡ndez,NaN,7.30
1,71,CasaNico-Sectra,50,10,07:00:00,09:00:00,f,2018-10-01 12:06:21.250135,t,Coventry,Teatinos,NaN,9.05
2,72,Av. Costanera AndrÃ©s Bello Providencia,60,10,00:00:00,23:55:00,t,2018-10-02 13:00:07.398848,t,Camino Del Valle Alto,Bandera,NaN,16.49
3,73,TramoIrarrazavalPO3,20,10,00:00:00,23:59:00,t,2018-10-12 15:16:48.442286,t,Exequiel FernÃ¡ndez,JosÃ© Pedro Alessandri,NaN,0.18
4,74,TramoIrarrazavalPO2,20,10,00:00:00,23:59:00,t,2018-10-12 15:17:41.926382,t,Pedro de Valdivia,Exequiel FernÃ¡ndez,NaN,0.49
5,75,TramoIrarrazavalPO1,20,10,00:00:00,23:59:00,t,2018-10-12 15:18:27.264914,t,Campo de Deportes,Pedro de Valdivia,NaN,0.37
6,76,TramoMaculNS3,20,10,00:00:00,23:59:00,t,2018-10-12 15:19:28.613460,t,Eduardo Castillo Velasco,Juan GÃ³mez Millas,NaN,0.29
7,77,TramoMaculNS1,20,10,00:00:00,23:59:00,t,2018-10-12 15:20:19.181767,t,IrarrÃ¡zaval,DublÃ© Almeyda,NaN,0.21
8,78,TramoMaculNS2,20,10,00:00:00,23:59:00,t,2018-10-12 15:21:07.224030,t,DublÃ© Almeyda,Eduardo Castillo Velasco,NaN,0.27